apiVersion: v1
kind: Service
metadata:
  name: newclicks-service

spec:
  type: NodePort

  selector:
    app: newclicks

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007